#!/usr/bin/python3
# -*- python -*-

from __future__ import print_function

import sys
sys.path += [ "/usr/share/unicsy/lib" ]

import os
import time
import hardware
import watchdog

class State:
    def __init__(m, bat):
        m.volt3 = bat.volt3
        m.perc3 = bat.perc3
        m.charge_now = bat.charge_now
        m.time = time.time()
        m.status = bat.status

class Man:
    def esc(m, s):
        print(chr(27)+s)

    def cls(m):
        m.esc("c")

    def disp(m, v):
        if v in m.states:
            old = m.states[v]
            dt = time.time() - old.time
            dc = (old.charge_now - m.bat.charge_now) / 1000
            print(v, "%.1f min ago" % (dt/60),
                  "%.6f Ah" % dc,
                  "%.6f A" % ((dc * 3600.)/dt) )

    def one_step(m):
        bat = m.bat
        bat.run()
        s = bat.summary()
        s2 = bat.handle_protect()
        if s2: s = s2

        if m.last_counter is None:
            aacur = 0
        else:
            # in mAh
            aacur = (bat.charge_now - m.last_counter) / (m.step/3600.)
            # WTF? Is that right?
        m.last_counter = bat.charge_now

        if not "startup" in m.states:
            m.states["startup"] = State(bat)
        if "last" in m.states:
            ls = m.states["last"].status
            if bat.status != ls:
                m.states[ls + "-" + bat.status] = State(bat)
            p2 = bat.perc3 // 10
            p1 = m.states["last"].perc3 // 10
            if p1 != p2:
                m.states["%s%d-%d" % (bat.status, p1, p2)] = State(bat)

        if False:
            print("utime=%.3f"% time.time(),
                  "batvolt=%.3f" % bat.volt,
                  "bativolt=%.3f" % bat.volt3,
                  "batperc=%.1f" % bat.perc,
                  "batiperc=%.1f" % bat.perc3,
                  "batcur=%.5f" % bat.current,
                  "batacur=%.5f" % bat.current_avg,
                  "bataacur=%f" % aacur,
                  "charge=%f" % bat.charge_now, file=bat_log)
        if True:
            m.capacity = 1785
            if bat.battery_empty and bat.battery_full:
                m.capacity = bat.battery_full-bat.battery_empty

            print("bat %.2f V %.2f %% |" % (bat.volt, bat.perc))
            print("int %.2f V %.2f %% |" % (bat.volt3, bat.perc3))
            print()
            print("now %.2f A %f Ah" % (bat.current_avg/1000, -bat.charge_now/1000))
            print()
            print("st %s b_st %s" % (bat.status, bat.b_status))
            m.disp("Full-Discharging")
            m.disp("Charging-Discharging")
            m.disp("Discharging-Charging")
            m.disp("Charging-Full")
            m.disp("startup")
            m.disp("Discharging9-8")
            m.disp("Discharging8-7")
            m.disp("Discharging3-2")
            m.disp("Charging2-3")
            m.disp("Charging7-8")
            m.disp("Charging8-9")

        if False:
            print("empty %s 3.5V %s 4V %s full %s |" % (bat.fmt(bat.battery_empty), bat.fmt(bat.battery_35V), bat.fmt(bat.battery_4V), bat.fmt(bat.battery_full)), file=sys.stderr)

            print(bat.guess_charge(bat.battery_empty, 0, m.capacity) + " to empty", file=sys.stderr)
            print(bat.guess_charge(bat.battery_35V, bat.percent(3.5) / 100., m.capacity) + " to 3.5V", file=sys.stderr)
            print(bat.guess_charge(bat.battery_4V, bat.percent(4.) / 100., m.capacity) + " or more -- to 4V", file=sys.stderr)
            print(bat.guess_charge(bat.battery_full, 1., m.capacity) + " to full", file=sys.stderr)

        m.states["last"] = State(bat)

    def run(m):
        m.bat = hardware.hw.battery
        m.last_counter = None
        m.states = {}
        m.step = 5
        while 1:
            m.cls()
            m.one_step()
            sys.stdout.flush()
            time.sleep(m.step)

m = Man()
m.run()
